### PR TITLE
update to streamio-ffmpeg 3.0.0

### PR DESCRIPTION
**Pull request by ingooooooo**
pass custom options as array instead of string for compatibility with streamio-ffmpeg 3.0.0; change default audio codec for mp4 from libfaac to aac

### CODE REVIEW

**Comment by esc** [comment]
@ingooooooo travis is red, was it you?

**Comment by ingooooooo** [comment]
@esc: problem fixed. (travis was using too old ruby version)

**Comment by esc** [comment]
Cool, @rheaton, can you merge and release?

**Comment by ingooooooo** [comment]
Is it possible to merge this, @rheaton or do you have comments?

**Pull request merged**
